# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp function to replace the for-loop inside the 'convertor_long_cut()' function
#'
#' @param time_seq a numeric vector of the time sequence
#' @param segment_onset_vec a numeric vector of onset
#' @param segment_offset_vec a numeric vector of offset
#' @param speaker_type_vec a character vector of speaker type
#' @return a named list of length 2
convertor_long_cut_loop <- function(time_seq, segment_onset_vec, segment_offset_vec, speaker_type_vec) {
    .Call(`_ChildRecordsR_convertor_long_cut_loop`, time_seq, segment_onset_vec, segment_offset_vec, speaker_type_vec)
}

#' Rcpp function to replace the for-loop inside the 'LENA.overlap()' function
#'
#' @param segment_onset_vec a numeric vector of onset
#' @param segment_offset_vec a numeric vector of offset
#' @param speaker_type_vec a character vector of speaker type
#' @return a named list of length 2
LENA_overlap_loop <- function(segment_onset_vec, segment_offset_vec, speaker_type_vec) {
    .Call(`_ChildRecordsR_LENA_overlap_loop`, segment_onset_vec, segment_offset_vec, speaker_type_vec)
}

